<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Bank;

class BankNameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $banks = [
            'AU Small Finance Bank',
            'Allahabad Bank',
            'Allahabad U.P Gramin Bank',
            'Ambarnath Jai Hind Cooperative Bank Limited',
            'Andhra Bank',
            'Airtel Payments Bank',
            'Andhra Pradesh Grameena Vikas Bank Ltd',
            'Ambajogai Peoples Co-operative Bank Ltd',
            'Ahmedabad District Co-operative Bank Ltd',
            'The Ahmedabad Mercantile Co-operative Bank Ltd',
            'Andhra Pragathi Grameena Bank',
            'Arunachal Pradesh Rural Bank',
            'Assam Gramin Vikash Bank',
            'Axis Bank',
            'Abhyudaya Co-operative Bank Ltd',
            'Ambajogai People\'s Co-operative Bank Ltd',
            'Almora Urban Co-operative Bank',
            'Apna Sahakari Bank Ltd',
            'Adv Shamraoji Shinde Satyashodhak Sahakari Bank Limited',
            'Bandhan Bank',
            'Bangiya Gramin Vikash Bank',
            'Bank of Bahrain and Kuwait',
            'Bank of Baroda',
            'Bank of Baroda - Corporate Banking',
            'Bank of Baroda - Retail Banking',
            'Bank of India',
            'Bank of Maharashtra',
            'Baroda Gujarat Gramin Bank',
            'Buldana Urban Co-operative Credit Society Ltd',
            'Baroda Rajasthan Kshetriya Gramin Bank',
            'Baroda UP Gramin Bank',
            'Bihar Gramin Bank',
            'Bombay Merchantile Bank',
            'Canara Bank',
            'Capital Small Finance Bank',
            'Catholic Syrian Bank Limited',
            'Central Bank of India',
            'Central Madhya Pradesh Gramin Bank',
            'Chaitanya Godavari Grameena Bank',
            'Chhattisgarh Rajya Gramin Bank',
            'Chungathara Service Co-operative Bank Ltd',
            'Citi Bank',
            'City Union Bank',
            'Coastal Local Area Bank Limited',
            'Corporation Bank',
            'Cosmos Bank',
            'CSB Bank',
            'Dakshin Bihar Gramin Bank',
            'HSBC Bank',
            'Dena Bank',
            'Dena Gujarat Gramin Bank',
            'Deogiri Nagari Sahakari Bank Ltd',
            'Deutsche Bank',
            'Development Credit Bank',
            'Dhanlaxmi Bank',
            'Digibank',
            'Dino Bank Ltd.',
            'Dombivli Nagari Sahakari Bank Ltd. (DNS)',
            'District Cooperative Bank',
            'DBS Bank',
            'ESAF Small Finance Bank',
            'Ellaquai Dehati Bank',
            'Equitas Small Finance Bank',
            'Federal Bank',
            'Fincare Small Finance Bank',
            'Fino Payments Bank Ltd.',
            'GS Mahanagar Co-op Bank Ltd',
            'Goa State Coop Bank Ltd',
            'Gramin Bank of Aryavart',
            'HDFC Bank',
            'Himachal Pradesh Gramin Bank',
            'ICICI Bank',
            'IDBI Bank',
            'IDFC Bank',
            'IDFC First Bank',
            'ING Vysya Bank',
            'Indian Bank',
            'Indian Overseas Bank',
            'IndusInd Bank',
            'J&K Bank Ltd.',
            'J&K Grameen Bank',
            'Jammu and Kashmir Bank',
            'Jana Small Finance Bank',
            'Jharkhand Gramin Bank',
            'Janata Sahakari Bank Ltd',
            'Karnataka Bank Ltd',
            'Karnataka Vikas Grameena Bank',
            'Karur Vysya Bank',
            'Kashi Gomti Samyut Gramin Bank',
            'Kaveri Grameena Bank',
            'Kerala Gramin Bank',
            'Kotak Bank',
            'Kotak Mahindra Bank',
            'Krishna Bhima Samruddhi Local Area Bank Ltd.',
            'Lakshmi Vilas Bank',
            'Langpi Dehangi Rural Bank',
            'Lokmangal Co-Operative Bank Limited',
            'Madhya Bihar Gramin Bank',
            'Madhyanchal Gramin Bank',
            'Maharashtra Gramin Bank',
            'Malwa Gramin Bank',
            'Manipur Rural Bank',
            'Meghalaya Rural Bank',
            'Mizoram Rural Bank',
            'Nagaland Rural Bank',
            'Nainital Bank',
            'Nainital District Co-Operative Bank',
            'Nagar Urban Co-Operative Bank Ltd',
            'Narmada Jhabua Gramin Bank',
            'North East Small Finance Bank',
            'Odisha Gramya Bank',
            'Oriental Bank of Commerce',
            'Pallavan Grama Bank',
            'Panchmahal District Co-operative Bank',
            'Pandyan Grama Bank',
            'Paschim Banga Gramin Bank',
            'Pavana Sahakari Bank Ltd.',
            'Paytm Payments Bank',
            'Post Office Saving Bank',
            'Pragathi Krishna Gramin Bank',
            'Prathama Bank',
            'Priyadarshani Nagari Sahakari Bank Ltd',
            'Puduvai Bharthiar Grama Bank',
            'Punjab & Maharashtra Cooperative Bank Ltd.',
            'Punjab & Sind Bank',
            'Punjab Gramin Bank',
            'Punjab National Bank - Corporate Banking',
            'Punjab National Bank - Retail Banking',
            'Purvanchal Bank',
            'Pravara Sahakari Bank Ltd',
            'RBL Bank',
            'Rajasthan Marudhara Gramin Bank',
            'Pithoragarh District Co-operative Bank',
            'Ratnagiri District Central Co-operative Bank Ltd.',
            'Samarth Sahakari Bank Limited',
            'Saptagiri Grameena Bank',
            'Saraswat Bank',
            'Sarva Haryana Gramin Bank',
            'Sarva UP Gramin Bank',
            'Saurashtra Gramin Bank',
            'Seva Vikas Co-Operative Bank Ltd.',
            'Shamrao Vitthal Co-operative Bank',
            'Shree Kadi Nagarik Sahakari Bank Ltd.',
            'Shri Chhatrapati Rajarshi Shahu Urban Co-Operative Bank Ltd',
            'Shri Ganesh Sahakari Bank Ltd',
            'Shri Gajanan Maharaj Urban Co Operative Bank',
            'Siddheshwar Urban Co-Operative Bank',
            'Sanmati Sahakari Bank Ltd.',
            'Solapur Janata Sahakari Bank Ltd',
            'South Indian Bank',
            'Standard Chartered',
            'State Bank of Bikaner & Jaipur',
            'State Bank of Hyderabad',
            'State Bank of India',
            'State Bank of Mysore',
            'State Bank of Patiala',
            'State Bank of Travancore',
            'Sterling Urban Co-operative Bank Ltd',
            'Subhadra Local Area Bank Ltd.',
            'Shivaji Nagari Sahakari Bank Paithan',
            'Shrimant Malojiraje Sahakari Bank Ltd',
            'SVC Co-operative Bank Ltd',
            'Shikshan Maharshi Dnyandev Mohekar Multistate Co Operative Credit Society Ltd',
            'Suryoday Small Finance Bank Limited',
            'Sutlej Gramin Bank',
            'Syndicate Bank',
            'Shivalik Mercantile Co-operative Bank Ltd.',
            'TJSB Sahakari Bank Ltd.',
            'Tamilnad Mercantile Bank Ltd.',
            'Telangana Grameena Bank',
            'Thane Bharat Sahakari Bank Ltd.',
            'The Akola Janata Commercial Co-operative Bank Ltd.',
            'The Nav Jeevan Co-operative Bank Ltd',
            'The Citizen Co-Operative Bank Ltd.',
            'The Delhi State Cooperative Bank Ltd',
            'The Yavatmal Urban Co-Operative Bank Ltd',
            'The Karad Urban Co-operative Bank Ltd',
            'The Satara District Central Co-operative Bank Ltd.',
            'The Kurmanchal Nagar Sahkari Bank',
            'The Malkapur Urban Co-Op. Bank Ltd',
            'Tripura Gramin Bank',
            'UCO Bank',
            'Unjha Nagarik Sahakari Bank LTD',
            'Ujjivan Small Finance Bank',
            'Union Bank of India',
            'United Bank of India',
            'Utkal Grameen Bank',
            'Utkarsh Small Finance Bank',
            'Uttar Banga Kshetriya Gramin Bank',
            'Uttar Bihar Gramin Bank',
            'Uttarakhand Gramin Bank',
            'Uttarakhand State Co-operative Bank Ltd.',
            'Udham Singh Nagar District Co-operative Bank Ltd.',
            'Vananchal Gramin Bank',
            'Vidharbha Konkan Gramin Bank',
            'Vikas Sahakari Bank Limited',
            'Vaishya Nagari Sahakari Bank Ltd',
            'Vidyanand Co-Operative Bank Limited',
            'Vijaya Bank',
            'Yes Bank Ltd',
            'Zila Sahkari Bank Ltd.',
            'The Jalgaon Peoples Co-Operative Bank Ltd',
            'The Chikhli Urban Co-Operative Bank Ltd',
            'The Vishweshwar Sahakari Bank Ltd',
            'Wai Urban Co-operative Bank Ltd',
            'The Varachha Co-operative Bank Ltd',
            'Pune District Central Co-Operative Bank Ltd',
            'The Mehsana Urban Co-Operative Bank Ltd',
            'The Banaskantha Mercantile Co-operative Bank Ltd',
            'DCB Bank Ltd',
            'India Post Payments Bank',
            'The Himachal Pradesh State Cooperative Bank Ltd',
            'The Kolhapur Urban Cooperative Bank Ltd',
            'GP Parsik Sahakari Bank Ltd',
            'Poornawadi Nagrik Sahakari Bank Ltd',
            'Nilambur Co-Operative Urban Bank Ltd',
            'Prerana Co-Operative Bank Ltd',
            'Shikshak Sahakari Bank Ltd',
            'The Kalyan Janata Sahakari Bank Ltd',
            'The Malad Sahakari Bank Ltd',
            'Ahmednagar Shahar Sahakari Bank Ltd',
            'The Bijnor Urban Co-Operative Bank Ltd',
            'Bassein Catholic Co-Operative Bank Ltd',
            'The Khamgaon Urban Co-Operative Bank Ltd',
            'Tukamai Mahila Urban Co-Operative Credit Society Ltd',
            'The Mogaveera Co-Operative Bank Ltd',
            'Panipat Urban Co-Operative Bank Ltd',
            'The Pandharpur Urban Co-Operative Bank Ltd',
            'Ner Urban Co-Operative Credit Society Ltd. Ner',
            'Ner Nababpur Urban Nidhi Ltd',
            'Pusad Urban Co-Operative Credit Society Ltd',
            'The Akola District Central Co-Operative Bank Ltd',
            'Municipal Co-Operative Bank Ltd.',
            'Mugberia Central Co-operative Bank Ltd',
            'Contai Co-Operative Bank Ltd',
            'Bilaspur Nagarik Sahakari Bank Ltd',
            'Jila Sahakari Kendriya Bank Maryadit',
            'Irinjalakuda Town Co-operative Bank Ltd',
        ];

        foreach ($banks as $bank) {
            Bank::create(['name' => $bank]);
        }
    }
}
