<?php

return [
    [
        'label' => 'BRANCH NAME',
        'name' => 'branch_name',
        'id' => 'branch_name',
        'type' => 'text',
        'required' => true,
    ],
    [
        'label' => 'BRANCH CODE',
        'name' => 'branch_code',
        'id' => 'branch_code',
        'type' => 'text',
        'required' => true,
    ],
    [
        'label' => 'OPEN DATE',
        'name' => 'open_date',
        'id' => 'date6',
        'type' => 'text',
        'default' => now()->format('d-m-Y'),
        'required' => false,
    ],
    [
        'label' => 'IFSC CODE',
        'name' => 'ifsc_code',
        'id' => 'ifsc_code',
        'type' => 'text',
        'required' => false,
    ],
     [
        'label' => 'SWIFT CODE',
        'name' => 'swift_code',
        'id' => 'swift_code',
        'type' => 'text',
        'required' => false,
    ],
    [
        'label' => 'ADDRESS LINE 1',
        'name' => 'address_line1',
        'id' => 'address_line1',
        'type' => 'text',
        'required' => true,
    ],
    [
        'label' => 'ADDRESS LINE 2',
        'name' => 'address_line2',
        'id' => 'address_line2',
        'type' => 'text',
        'required' => false,
    ],
    [
        'label' => 'COUNTRY',
        'name' => 'country',
        'id' => 'country',
        'type' => 'text',
        'required' => true,
        'default' => 'India',
    ],
    [
        'label' => 'STATE',
        'name' => 'state',
        'id' => 'stateDropdown',
        'type' => 'select',
        'required' => true,
        'dynamic' => true,
        'options_key' => 'states', // 👈 used to match controller data
    ],
    [
        'label' => 'CITY',
        'name' => 'city',
        'id' => 'city',
        'type' => 'text',
        'required' => true,
    ],
    [
        'label' => 'PINCODE',
        'name' => 'pincode',
        'id' => 'pincode',
        'type' => 'text',
        'required' => true,
    ],
    [
        'label' => 'EMAIL ID',
        'name' => 'contact_email',
        'id' => 'contact_email',
        'type' => 'email',
        'required' => false,
    ],
    [
        'label' => 'CONTACT NO.',
        'name' => 'mobile_no',
        'id' => 'mobile_no',
        'type' => 'number',
        'maxlength' => '10',
        'minlength' => '10',
        'pattern' => '[0-9]{10}',
        'required' => true,
    ],

    [
        'label' => 'LANDLINE NO.',
        'name' => 'landline_no',
        'id' => 'landline_no',
        'type' => 'text',
        'required' => false,
    ],
    [
        'label' => 'GST NO.',
        'name' => 'gst_no',
        'id' => 'gst_no',
        'type' => 'text',
        'required' => false,
    ],
    [
        'label' => 'PERMISSION LETTER',
        'name' => 'permission_letter',
        'id' => 'permission_letter',
        'type' => 'file',  
        'required' => false,
    ],
    [
        'label' => 'DISABLE RECHARGE / BILL PAYMENT',
        'name' => 'disable_recharge',
        'id' => 'disable_recharge',
        'type' => 'radio',
        'required' => true,
        'default' => 'yes',
        'options' => [
            'yes' => 'Yes',
            'no' => 'No',
        ],
    ],
    [
        'label' => 'DISABLE NEFT',
        'name' => 'disable_neft',
        'type' => 'radio',
        'id' => 'disable_neft',
        'required' => true,
        'default' => 'no',
        'options' => [
            'yes' => 'Yes',
            'no' => 'No',
        ],
    ],
       
];
