<?php

return [

    // Membership Type (unnamed section)
    [
        [
            'label' => 'MEMBERSHIP TYPE',
            'name' => 'membership_type',
            'id' => 'membership_type',
            'type' => 'select',
            'required' => true,
            'default' => 'regular',
            'options' => [
                'nominal' => 'Nominal Membership',
                'regular' => 'Regular Membership',
            ],
        ],

        [
            'label' => 'ADVISOR/ STAFF',
            'name' => 'general_advisor_staff',
            'id' => 'advisor_staff',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'GROUP',
            'name' => 'general_group',
            'id' => 'group',
            'type' => 'select',
            'required' => false,
            'options' => [
                'group1' => 'Group 1',
                'group2' => 'Group 2',
            ],
        ],
        [
            'label' => 'BRANCH',
            'name' => 'general_branch',
            'id' => 'branch',
            'type' => 'select',
            'required' => true,
            'dynamic' => true,
            'options_key' => 'branch',
        ],
        [
            'label' => 'ENROLLMENT DATE',
            'name' => 'general_enrollment_date',
            'id' => 'date',
            'type' => 'text',
            'required' => true,
            'default' => now()->format('d-m-Y'), // <- This line
        ],

    ],

    'CUSTOMER_INFO' => [
        [
            'label' => 'TITLE',
            'name' => 'member_info_title',
            'id' => 'title',
            'type' => 'radio',
            'required' => true,
            'options' => [
                'Md' => 'Md.',
                'Mr' => 'Mr.',
                'Ms' => 'Ms.',
                'Mrs' => 'Mrs.',
            ],
        ],
        [
            'label' => 'GENDER',
            'name' => 'member_info_gender',
            'id' => 'gender',
            'type' => 'radio',
            'required' => true,
            'options' => [
                'male' => 'Male',
                'female' => 'Female',
                'other' => 'Other',
            ],
        ],
        [
            'label' => 'FIRST NAME',
            'name' => 'member_info_first_name',
            'id' => 'first_name',
            'type' => 'text',
            'required' => true,
        ],
        [
            'label' => 'MIDDLE NAME',
            'name' => 'member_info_middle_name',
            'id' => 'middle_name',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'LAST NAME',
            'name' => 'member_info_last_name',
            'id' => 'last_name',
            'type' => 'text',
            'required' => true,
        ],
        [
            'label' => 'DATE OF BIRTH',
            'name' => 'member_info_dob',
            'id' => 'datep',
            'type' => 'text',
            'required' => true,
        ],
        [
            'label' => 'QUALIFICATION',
            'name' => 'member_info_qualification',
            'id' => 'qualification',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'OCCUPATION',
            'name' => 'member_info_occupation',
            'id' => 'occupation',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'MONTHLY INCOME',
            'name' => 'member_info_monthly_income',
            'id' => 'monthly_income',
            'type' => 'number',
            'required' => false,
        ],
        [
            'label' => 'OLD CUSTOMER NO (IF ANY)',
            'name' => 'member_info_old_member_no',
            'id' => 'old_member_no',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'FATHER NAME',
            'name' => 'member_info_father_name',
            'id' => 'father_name',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'MOTHER NAME',
            'name' => 'member_info_mother_name',
            'id' => 'mother_name',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'HUSBAND/ WIFE NAME',
            'name' => 'member_info_spouse_name',
            'id' => 'spouse_name',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'HUSBAND/ WIFE DOB',
            'name' => 'member_info_spouse_dob',
            'id' => 'datep2',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'MOBILE NO',
            'name' => 'member_info_mobile_no',
            'id' => 'mobile_no',
            'type' => 'number',
            'maxlength' => '10',
            'minlength' => '10',
            'pattern' => '[0-9]{10}',
            'required' => true,
        ],
        [
            'label' => 'COLLECTION TIME',
            'name' => 'member_info_collection_time',
            'id' => 'collection_time',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'MARITAL STATUS',
            'name' => 'member_info_marital_status',
            'id' => 'marital_status',
            'type' => 'select',
            'required' => false,
            'options' => [
                'single' => 'Single',
                'married' => 'Married',
                'divorced' => 'Divorced',
                'widowed' => 'Widowed',
                'separated' => 'Separated',
            ],
        ],
        [
            'label' => 'CUSTOMER RELIGION',
            'name' => 'member_info_religion',
            'id' => 'religion',
            'type' => 'select',
            'required' => false,
            'dynamic' => true,
            'options_key' => 'religion',
        ],
        [
            'label' => 'EMAIL',
            'name' => 'member_info_email',
            'id' => 'email',
            'type' => 'email',
            'required' => false,
        ],
    ],

    // Member Address
    'CUSTOMER_CORRESPONDENCE_ADDRESS' => [
        [
            'label' => 'ADDRESS LINE 1',
            'name' => 'member_address_line_1',
            'id' => 'address_line_1',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'ADDRESS LINE 2',
            'name' => 'member_address_line_2',
            'id' => 'address_line_2',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'PARA',
            'name' => 'member_address_para',
            'id' => 'para',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'WARD',
            'name' => 'member_address_ward',
            'id' => 'ward',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'PANCHAYAT',
            'name' => 'member_address_panchayat',
            'id' => 'panchayat',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'AREA',
            'name' => 'member_address_area',
            'id' => 'area',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'LANDMARK',
            'name' => 'member_address_landmark',
            'id' => 'landmark',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'CITY / DISTRICT',
            'name' => 'member_address_city_district',
            'id' => 'city_district',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'STATE',
            'name' => 'member_address_state',
            'id' => 'stateDropdown',
            'type' => 'select',
            'required' => true,
            'dynamic' => true,
            'options_key' => 'states',
        ],
        [
            'label' => 'PINCODE',
            'name' => 'member_address_pincode',
            'id' => 'address_pincode',
            'type' => 'number',
            'required' => true,
        ],
        [
            'label' => 'COUNTRY',
            'name' => 'member_address_country',
            'id' => 'country',
            'type' => 'text',
            'required' => true,
            'default' => 'India',

        ],

    ],

    // Permanent Address
    'CUSTOMER_PERMANENT_ADDRESS' => [
        [
            'label' => 'ADDRESS',
            'name' => 'member_address_address',
            'id' => 'address',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'CITY',
            'name' => 'member_perm_address_city',
            'id' => 'city',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'STATE',
            'name' => 'member_perm_address_state',
            'id' => 'state',
            'type' => 'select',
            'required' => false,
            'dynamic' => true,
            'options_key' => 'states',
        ],
        [
            'label' => 'PINCODE',
            'name' => 'member_perm_address_pincode',
            'id' => 'perm_address_pincode',
            'type' => 'number',
            'required' => false,
        ],
    ],

    // GPS Location
    'CUSTOMER_ADDRESS_GPS_LOCATION' => [
        [
            'label' => 'LOCATION LATITUDE',
            'name' => 'member_gps_location_latitude',
            'id' => 'location_latitude',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'LOCATION LONGITUDE',
            'name' => 'member_gps_location_longitude',
            'id' => 'location_longitude',
            'type' => 'number',
            'required' => false,
        ],
    ],

    // KYC Info
    'CUSTOMER_KYC' => [
        [
            'label' => 'AADHAAR NO.',
            'name' => 'member_kyc_aadhaar_no',
            'id' => 'aadhaar_no',
            'type' => 'text',
            'required' => true,
            'maxlength' => 12,
            'pattern' => '\d{12}',
        ],

        [
            'label' => 'VOTER ID NO.',
            'name' => 'member_kyc_voter_id_no',
            'id' => 'voter_id_no',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'PAN',
            'name' => 'member_kyc_pan_no',
            'id' => 'pan_no',
            'type' => 'text',
            'required' => true,
            'maxlength' => 10,
            'pattern' => '[A-Z]{5}[0-9]{4}[A-Z]{1}',
        ],
        [
            'label' => 'RATION CARD NO.',
            'name' => 'member_kyc_ration_card_no',
            'id' => 'ration_card_no',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'METER NO.',
            'name' => 'member_kyc_meter_no',
            'id' => 'meter_no',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'CI NO.',
            'name' => 'member_kyc_ci_no',
            'id' => 'ci_no',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'CI RELATION',
            'name' => 'member_kyc_ci_relation',
            'id' => 'ci_relation',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'DL NO.',
            'name' => 'member_kyc_dl_no',
            'id' => 'dl_no',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'PASSPORT NO.',
            'name' => 'member_kyc_passport_no',
            'id' => 'passport_no',
            'type' => 'text',
            'required' => false,
        ],
    ],

    // KYC Documents
    'CUSTOMER_KYC_DOCUMENTS' => [
        [
            'label' => 'PHOTO',
            'name' => 'member_kyc_photo',
            'id' => 'photo',
            'type' => 'file',
            'required' => false,
            'accept' => 'image/*',
        ],
        [
            'label' => 'SIGNATURE',
            'name' => 'member_kyc_signature',
            'id' => 'signature',
            'type' => 'file',
            'required' => false,
            'accept' => 'image/*',
        ],
        [
            'label' => 'ID PROOF',
            'name' => 'member_kyc_id_proof',
            'id' => 'id_proof',
            'type' => 'file',
            'required' => false,
            'accept' => 'image/*,.pdf',
        ],
        [
            'label' => 'ID PROOF BACK',
            'name' => 'member_kyc_id_proof_back',
            'id' => 'id_proof_back',
            'type' => 'file',
            'required' => false,
            'accept' => 'image/*,.pdf',
        ],
        [
            'label' => 'ADDRESS PROOF',
            'name' => 'member_kyc_address_proof',
            'id' => 'address_proof',
            'type' => 'file',
            'required' => false,
            'accept' => 'image/*,.pdf',
        ],
        [
            'label' => 'ADDRESS PROOF BACK',
            'name' => 'member_kyc_address_proof_back',
            'id' => 'address_proof_back',
            'type' => 'file',
            'required' => false,
            'accept' => 'image/*,.pdf',
        ],
        [
            'label' => 'PAN',
            'name' => 'member_kyc_pan_number',
            'id' => 'pan_number',
            'type' => 'file',
            'required' => false,
            'accept' => 'image/*,.pdf',
        ],
    ],

    // Nominee Info
    'NOMINEE_INFO' => [
        [
            'label' => 'NOMINEE NAME',
            'name' => 'nominee_name',
            'id' => 'nominee_name',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'NOMINEE RELATION',
            'name' => 'nominee_relation',
            'id' => 'nominee_relation',
            'type' => 'select', // changed from 'text' to 'select'
            'required' => false,
            'options' => [
                '' => 'Select Relation',
                'father' => 'Father',
                'mother' => 'Mother',
                'son' => 'Son',
                'daughter' => 'Daughter',
                'spouse' => 'Spouse (Husband/ Wife)',
                'husband' => 'Husband',
                'wife' => 'Wife',
                'brother' => 'Brother',
                'sister' => 'Sister',
                'daughter_in_law' => 'Daughter in Law',
                'brother_in_law' => 'Brother in Law',
                'grand_daughter' => 'Grand Daughter',
                'grand_son' => 'Grand Son',
                'nephew' => 'Nephew',
                'niece' => 'Niece',
                'other' => 'Other'
            ]
        ],

        [
            'label' => 'NOMINEE MOBILE NO.',
            'name' => 'nominee_mobile_no',
            'id' => 'nominee_mobile_no',
            'type' => 'number',
            'maxlength' => '10',
            'minlength' => '10',
            'pattern' => '[0-9]{10}',
            'required' => false,
        ],
        [
            'label' => 'GENDER',
            'name' => 'nominee_gender',
            'id' => 'nominee_gender',
            'type' => 'radio',
            'required' => false,
            'options' => ["Male" => 'Male', "Female" => 'Female', "Other" => 'Other'],
        ],
        [
            'label' => 'NOMINEE DOB',
            'name' => 'nominee_dob',
            'id' => 'datep4',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'NOMINEE AADHAAR NO.',
            'name' => 'nominee_aadhaar_no',
            'id' => 'nominee_aadhaar_no',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'NOMINEE VOTER ID NO.',
            'name' => 'nominee_voter_id_no',
            'id' => 'nominee_voter_id_no',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'NOMINEE PAN',
            'name' => 'nominee_pan_no',
            'id' => 'nominee_pan_no',
            'type' => 'text',
            'required' => false,
            'maxlength' => 10,
            'pattern' => '[A-Z]{5}[0-9]{4}[A-Z]{1}',
        ],
        [
            'label' => 'NOMINEE RATION CARD NO.',
            'name' => 'nominee_ration_card_no',
            'id' => 'nominee_ration_card_no',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'NOMINEE ADDRESS',
            'name' => 'nominee_address',
            'id' => 'nominee_address',
            'type' => 'text',
            'required' => false,
        ],
    ],
    // Extra Settings
    'EXTRA_SETTINGS' => [
        [
            'label' => 'SMS',
            'name' => 'extra_sms',
            'id' => 'sms',
            'type' => 'checkbox',
            'required' => false,
            'default' => 0,
        ],
    ],

    // Membership Charges
    'MEMBERSHIP_CHARGES_ (IF ANY) ' => [
        [
            'label' => 'TRANSACTION DATE',
            'name' => 'charges_transaction_date',
            'id' => 'date5',
            'type' => 'string',
            'required' => true,
            'default' => now()->format('d-m-Y'), // <- This line

        ],

        [
            'label' => 'MEMBERSHIP FEE',
            'name' => 'charges_membership_fee',
            'id' => 'membership_fee',
            'type' => 'number',
            'required' => false,
        ],
        [
            'label' => 'NET FEE TO COLLECT',
            'name' => 'charges_net_fee',
            'id' => 'net_fee',
            'type' => 'number',
            'required' => true,
            'default' => 10, // Default value set to 100
        ],
        [
            'label' => 'REMARKS(IF ANY) ',
            'name' => 'charges_remarks',
            'id' => 'remarks',
            'type' => 'text',
            'required' => false,
        ],
        [
            'label' => 'PAYMENT MODE',
            'name' => 'charges_pay_mode',
            'id' => 'pay_mode',
            'type' => 'radio',
            'required' => false,
            'options' => [
                'cash' => 'Cash',
                'online' => 'Online Tr.',
                'cheque' => 'Cheque',
            ],
        ],
    ],

    'online Tr' => [
        [
            'label' => 'TRANSFER DATE ',
            'name' => 'online_transfer_date',
            'id' => 'date',
            'type' => 'text',
            'required' => true,
            'default' =>  now()->format('d-m-Y'),
        ],
        [
            'label' => 'UTR/ TRANSACTION NO. ',
            'name' => 'online_utr_no',
            'id' => 'online_utr_no',
            'type' => 'text',
            'required' => true,
            'placeholder' => 'Enter UTR/ Transaction No',
        ],
        [
            'label' => 'TRANSFER MODE ',
            'name' => 'online_transfer_mode',
            'id' => 'online_transfer_mode',
            'type' => 'select',
            'options' => [
                'imps' => 'IMPS',
                'vpa' => 'VPA',
                'neft_rtgs' => 'NEFT/RTGS',
            ],
            'required' => true,
        ],
    ],

    'cheque' => [
        [
            'label' => 'BANK NAME',
            'name' => 'bank_id', // link to banks table
            'id' => 'bank_id',
            'type' => 'custom',
            'component' => 'searchable-dropdown',
            'required' => true,
        ],
        [
            'label' => 'CHEQUE NO. ',
            'name' => 'cheque_no',
            'id' => 'cheque_no',
            'type' => 'text',
            'required' => true,
            'placeholder' => 'Enter Cheque No.',
        ],
        [
            'label' => 'CHEQUE DATE ',
            'name' => 'cheque_date',
            'id' => 'cheque_date',
            'id' => 'date',
            'type' => 'text',
            'required' => true,
            'default' =>  now()->format('d-m-Y'),
        ],
    ],
];
