<?php

return 
[
    [
        'label' => 'ENROLLMENT DATE',
        'name' => 'enrollment_date',
        'id' => 'date',
        'type' => 'text',
        'required' => true,
        'default' => now()->format('d-m-Y'),
    ],
    [
        'label' => 'TITLE',
        'name' => 'title',
        'id' => 'title',
        'type' => 'radio',
        'required' => true,
        'options' => [
            'md' => 'Md.',
            'mr' => 'Mr.',
            'ms' => 'Ms.',
            'mrs' => 'Mrs.',
        ],
    ],
    [
        'label' => 'GENDER',
        'name' => 'gender',
        'id' => 'gender',
        'type' => 'radio',
        'required' => true,
        'options' => [
            'male' => 'Male',
            'female' => 'Female',
            'other' => 'Other',
        ],
    ],
    [
        'label' => 'FIRST NAME',
        'name' => 'first_name',
        'id' => 'first_name',
        'type' => 'text',
        'required' => true,
        'placeholder' => 'Enter First Name',
    ],
    [
        'label' => 'LAST NAME',
        'name' => 'last_name',
        'id' => 'last_name',
        'type' => 'text',
        'required' => false,
        'placeholder' => 'Enter Last Name',
    ],
    [
        'label' => 'DATE OF BIRTH',
        'name' => 'dob',
        'id' => 'datep',
        'type' => 'text', 
        'required' => true,
    ],
    [
        'label' => 'FATHER NAME',
        'name' => 'father_name',
        'id' => 'father_name',
        'type' => 'text',
        'required' => true,
        'placeholder' => 'Enter Father Name',
    ],
    [
        'label' => 'AADHAAR NO.',
        'name' => 'aadhaar_no',
        'id' => 'aadhaar_no',
        'type' => 'text',
        'required' => false,
        'placeholder' => 'Enter Aadhaar No.',
    ],
    [
        'label' => 'ADDRESS',
        'name' => 'address',
        'id' => 'address',
        'type' => 'text',
        'required' => true,
        'placeholder' => 'Enter Address',
    ],
];
